import type { RedditPost } from './types'

function hoursAgo(h: number): Date {
  return new Date(Date.now() - h * 3600 * 1000)
}

const MOCK_POSTS: Record<string, RedditPost[]> = {
  NVDA: [
    { id: 't3_nvda01', permalink: 'https://reddit.com/r/stocks/comments/nvda01', subreddit: 'stocks', author: 'gpu_bull', title: 'NVDA earnings absolutely crushed it again — $0.89 EPS vs $0.83 expected', body: 'AI demand is insane right now. Data center revenue up 427% YoY. Jensen delivered again. This company is a money printer.', upvotes: 2341, commentCount: 187, postedAt: hoursAgo(3) },
    { id: 't3_nvda02', permalink: 'https://reddit.com/r/investing/comments/nvda02', subreddit: 'investing', author: 'chip_watcher', title: 'Blackwell architecture is way ahead of the competition — no one is close to NVDA data center margins', body: 'AMD MI300X is solid but NVDA has the software ecosystem advantage (CUDA) that takes years to replicate. The moat is real.', upvotes: 1870, commentCount: 143, postedAt: hoursAgo(5) },
    { id: 't3_nvda03', permalink: 'https://reddit.com/r/wallstreetbets/comments/nvda03', subreddit: 'wallstreetbets', author: 'tendies_incoming', title: 'Just bought more NVDA on the dip — this is the picks and shovels play of the AI era', body: 'Every AI company needs NVDA chips. There is no alternative at scale. Loading up calls for next quarter.', upvotes: 4120, commentCount: 512, postedAt: hoursAgo(2) },
    { id: 't3_nvda04', permalink: 'https://reddit.com/r/stocks/comments/nvda04', subreddit: 'stocks', author: 'value_skeptic', title: 'NVDA at 35x revenue is hard to justify fundamentally — either AI capex accelerates or this corrects hard', body: 'I respect the execution but the valuation pricing in perfection for 5 years. Any macro slowdown hits this hardest.', upvotes: 876, commentCount: 234, postedAt: hoursAgo(8) },
    { id: 't3_nvda05', permalink: 'https://reddit.com/r/investing/comments/nvda05', subreddit: 'investing', author: 'semi_analyst', title: 'Export restrictions to China could significantly impact NVDA data center revenue — not priced in imo', body: 'H20 chip restrictions are tightening. China was ~20% of data center revenue. If this escalates, estimates need to come down.', upvotes: 1203, commentCount: 189, postedAt: hoursAgo(6) },
    { id: 't3_nvda06', permalink: 'https://reddit.com/r/SecurityAnalysis/comments/nvda06', subreddit: 'SecurityAnalysis', author: 'deep_dive_dan', title: "NVDA gross margins at 78% are insane for a chip company — this is a software-like business", body: 'When your software stack (CUDA, cuDNN, TensorRT) creates lock-in, you can charge software margins on hardware. Brilliant.', upvotes: 934, commentCount: 76, postedAt: hoursAgo(10) },
    { id: 't3_nvda07', permalink: 'https://reddit.com/r/stocks/comments/nvda07', subreddit: 'stocks', author: 'bear_thesis_2024', title: 'AMD and custom silicon from hyperscalers will eat into NVDA margins in 2 years', body: 'Google TPUs, AWS Trainium, Microsoft Maia. Hyperscalers are spending billions to reduce NVDA dependency. The moat will narrow.', upvotes: 654, commentCount: 198, postedAt: hoursAgo(12) },
    { id: 't3_nvda08', permalink: 'https://reddit.com/r/wallstreetbets/comments/nvda08', subreddit: 'wallstreetbets', author: 'jensen_fan_club', title: 'Jensen Huang is a generational CEO — the execution at NVIDIA over the last 5 years has been unreal', body: 'From gaming GPU company to the backbone of AI infrastructure. The pivot was perfectly timed and perfectly executed.', upvotes: 3210, commentCount: 267, postedAt: hoursAgo(4) },
    { id: 't3_nvda09', permalink: 'https://reddit.com/r/investing/comments/nvda09', subreddit: 'investing', author: 'insider_watcher', title: 'Insider selling has been heavy at NVDA — when executives sell this aggressively it is usually a signal', body: 'CFO and several VPs sold over $200M in stock this quarter. They know the valuation better than anyone.', upvotes: 1102, commentCount: 312, postedAt: hoursAgo(7) },
    { id: 't3_nvda10', permalink: 'https://reddit.com/r/stocks/comments/nvda10', subreddit: 'stocks', author: 'curious_investor', title: "What's everyone's price target for NVDA end of year?", body: 'Bulls saying $200, bears saying $80. Curious what the consensus here is. I have a small position and wondering whether to add.', upvotes: 445, commentCount: 423, postedAt: hoursAgo(9) },
  ],

  TSLA: [
    { id: 't3_tsla01', permalink: 'https://reddit.com/r/stocks/comments/tsla01', subreddit: 'stocks', author: 'ev_bear', title: "TSLA market share in EVs is shrinking quarter over quarter — BYD is eating their lunch in China", body: 'Q1 deliveries down again YoY. BYD outsells Tesla globally now. The premium is gone in the fastest growing EV market.', upvotes: 2890, commentCount: 445, postedAt: hoursAgo(2) },
    { id: 't3_tsla02', permalink: 'https://reddit.com/r/wallstreetbets/comments/tsla02', subreddit: 'wallstreetbets', author: 'musk_watcher', title: "Elon's political involvement is costing Tesla customers — I know 3 people who switched to Rivian", body: 'Brand damage is real and measurable. Consumer sentiment surveys are showing significant negative shift among previous Tesla advocates.', upvotes: 5340, commentCount: 891, postedAt: hoursAgo(1) },
    { id: 't3_tsla03', permalink: 'https://reddit.com/r/investing/comments/tsla03', subreddit: 'investing', author: 'fsd_believer', title: 'Full Self-Driving V12 on HW4 is genuinely impressive — closer to level 3 than anything else on the road', body: 'Tested it myself for 2 weeks. City driving is dramatically better than V11. The improvement rate is accelerating.', upvotes: 1234, commentCount: 334, postedAt: hoursAgo(5) },
    { id: 't3_tsla04', permalink: 'https://reddit.com/r/SecurityAnalysis/comments/tsla04', subreddit: 'SecurityAnalysis', author: 'valuation_hawk', title: 'TSLA priced at 80x earnings while growing deliveries 2% YoY — this is not a growth stock anymore', body: 'The multiple was justified by 50%+ growth. At 2% delivery growth, this is a premium car company with a sky-high multiple. Math does not work.', upvotes: 1876, commentCount: 276, postedAt: hoursAgo(6) },
    { id: 't3_tsla05', permalink: 'https://reddit.com/r/stocks/comments/tsla05', subreddit: 'stocks', author: 'energy_bull', title: "Tesla's energy storage business is massively undervalued — Megapack backlog is enormous", body: 'Energy segment growing 60% YoY with improving margins. This alone could justify a significant chunk of the market cap.', upvotes: 987, commentCount: 156, postedAt: hoursAgo(8) },
    { id: 't3_tsla06', permalink: 'https://reddit.com/r/wallstreetbets/comments/tsla06', subreddit: 'wallstreetbets', author: 'robotaxi_ape', title: 'Robotaxi launch in Austin could be a massive catalyst if it goes well', body: 'June launch date confirmed. If Cybercab works as demonstrated, this rewrites the entire Tesla thesis from car maker to autonomous fleet.', upvotes: 6120, commentCount: 743, postedAt: hoursAgo(3) },
    { id: 't3_tsla07', permalink: 'https://reddit.com/r/investing/comments/tsla07', subreddit: 'investing', author: 'competition_analyst', title: 'Tesla is competing with EVs, all car makers, AND Waymo in robotaxi — incredibly tough position', body: 'Name one other company facing this many competitive fronts simultaneously. The execution required is almost impossible to sustain.', upvotes: 1543, commentCount: 234, postedAt: hoursAgo(9) },
    { id: 't3_tsla08', permalink: 'https://reddit.com/r/stocks/comments/tsla08', subreddit: 'stocks', author: 'model_y_buyer', title: 'Model Y refresh is nice but too little too late — competition has caught up and the premium is gone', body: 'Tested the refreshed Model Y next to BYD Seal and Hyundai Ioniq 6. The gap in value proposition has closed dramatically.', upvotes: 876, commentCount: 198, postedAt: hoursAgo(11) },
    { id: 't3_tsla09', permalink: 'https://reddit.com/r/wallstreetbets/comments/tsla09', subreddit: 'wallstreetbets', author: 'options_vol_trader', title: 'TSLA options volume is insane today — someone making a massive bet ahead of delivery numbers', body: 'Unusual call activity at the $200 strike for next month. Either someone knows something or this is a big speculative play.', upvotes: 2340, commentCount: 512, postedAt: hoursAgo(4) },
    { id: 't3_tsla10', permalink: 'https://reddit.com/r/investing/comments/tsla10', subreddit: 'investing', author: 'long_term_holder', title: "Can't believe people are still holding through all the brand damage — fundamentals have deteriorated significantly", body: 'Margins down, volume flat, brand damaged, CEO distracted. The thesis that made TSLA worth 100x earnings no longer exists.', upvotes: 2134, commentCount: 567, postedAt: hoursAgo(7) },
  ],

  AAPL: [
    { id: 't3_aapl01', permalink: 'https://reddit.com/r/stocks/comments/aapl01', subreddit: 'stocks', author: 'supply_chain_watcher', title: 'iPhone 16 cycle is stronger than expected — supply chain data from Asia is very positive', body: 'Component orders from Foxconn and Pegatron up significantly versus iPhone 15 at this point in cycle. Bullish indicator for Q2 revenue.', upvotes: 1432, commentCount: 198, postedAt: hoursAgo(4) },
    { id: 't3_aapl02', permalink: 'https://reddit.com/r/investing/comments/aapl02', subreddit: 'investing', author: 'services_growth', title: 'AAPL services revenue growing 15% YoY is great but hardware is flat — becoming a services company', body: 'App Store, Apple TV+, iCloud, Apple Pay. These margins are 70%+. The mix shift is gradual but it is happening every quarter.', upvotes: 876, commentCount: 134, postedAt: hoursAgo(6) },
    { id: 't3_aapl03', permalink: 'https://reddit.com/r/wallstreetbets/comments/aapl03', subreddit: 'wallstreetbets', author: 'apple_ecosystem', title: 'Apple Intelligence is driving real upgrade cycles — the installed base monetization story is intact', body: 'People with iPhone 13 and below are upgrading for AI features. This was the missing catalyst and it is finally here.', upvotes: 2100, commentCount: 312, postedAt: hoursAgo(3) },
    { id: 't3_aapl04', permalink: 'https://reddit.com/r/SecurityAnalysis/comments/aapl04', subreddit: 'SecurityAnalysis', author: 'eu_regulatory_risk', title: 'EU hammering Apple on DMA compliance — fine risk is real and app store economics are changing', body: 'Forced sideloading, browser choice screens, NFC opening. The EU regulatory assault on Apple is systematic and accelerating.', upvotes: 1203, commentCount: 167, postedAt: hoursAgo(8) },
    { id: 't3_aapl05', permalink: 'https://reddit.com/r/investing/comments/aapl05', subreddit: 'investing', author: 'pe_watcher', title: 'AAPL at 28x earnings is expensive for single digit growth — the buyback is the main thesis now', body: 'Without the $90B buyback program, AAPL would be trading at a significant discount to this level. The buyback is load-bearing.', upvotes: 654, commentCount: 178, postedAt: hoursAgo(10) },
    { id: 't3_aapl06', permalink: 'https://reddit.com/r/stocks/comments/aapl06', subreddit: 'stocks', author: 'ecosystem_moat', title: "Apple's moat is the ecosystem — switcher rate is near zero and has been for a decade", body: 'iMessage lock-in, AirDrop, AirPlay, Apple Watch, iCloud sync. The switching cost compounds with each product you add to the ecosystem.', upvotes: 1876, commentCount: 243, postedAt: hoursAgo(5) },
    { id: 't3_aapl07', permalink: 'https://reddit.com/r/investing/comments/aapl07', subreddit: 'investing', author: 'tim_cook_critic', title: "Cook has been CEO 13 years and no major new product category since AirPods — where's the next iPhone?", body: 'Vision Pro is a flop commercially. The pipeline looks empty. Apple is great at execution but innovation seems to have stalled.', upvotes: 1102, commentCount: 312, postedAt: hoursAgo(9) },
    { id: 't3_aapl08', permalink: 'https://reddit.com/r/stocks/comments/aapl08', subreddit: 'stocks', author: 'india_growth', title: "India is becoming AAPL's next growth engine — revenue there up 35% last quarter", body: 'New manufacturing in India, expanding retail stores, growing middle class. The China over-reliance risk is being hedged at the same time.', upvotes: 987, commentCount: 145, postedAt: hoursAgo(7) },
    { id: 't3_aapl09', permalink: 'https://reddit.com/r/investing/comments/aapl09', subreddit: 'investing', author: 'long_term_compare', title: 'Anyone have thoughts on AAPL vs MSFT as a 5-year hold? Both feel safe but which has more upside?', body: 'I am 60/40 leaning MSFT because of Azure AI growth but AAPL has the better moat. Hard choice at current valuations.', upvotes: 445, commentCount: 387, postedAt: hoursAgo(11) },
    { id: 't3_aapl10', permalink: 'https://reddit.com/r/SecurityAnalysis/comments/aapl10', subreddit: 'SecurityAnalysis', author: 'vision_pro_analyst', title: 'Vision Pro flopped commercially but the technology is real — Apple will keep iterating until form factor works', body: 'At $3499, it was never going to sell mass market. This is the iPhone 1 moment for spatial computing. Gen 3 or 4 will be the real product.', upvotes: 765, commentCount: 134, postedAt: hoursAgo(12) },
  ],

  MSFT: [
    { id: 't3_msft01', permalink: 'https://reddit.com/r/stocks/comments/msft01', subreddit: 'stocks', author: 'azure_growth', title: 'Azure grew 33% last quarter and AI services attachment rate is accelerating — MSFT is the enterprise AI default', body: 'Fortune 500 companies are not going to rebuild their infrastructure. Azure wins by default when they want to add AI to existing Microsoft stacks.', upvotes: 2134, commentCount: 234, postedAt: hoursAgo(3) },
    { id: 't3_msft02', permalink: 'https://reddit.com/r/investing/comments/msft02', subreddit: 'investing', author: 'copilot_thesis', title: 'Microsoft Copilot rolling out across Fortune 500 — pure margin expansion on top of existing relationships', body: '$30/user/month on top of existing Office 365 subscriptions. Enterprise AI monetization is cleaner than any other company in the space.', upvotes: 1876, commentCount: 198, postedAt: hoursAgo(5) },
    { id: 't3_msft03', permalink: 'https://reddit.com/r/SecurityAnalysis/comments/msft03', subreddit: 'SecurityAnalysis', author: 'satya_capital_alloc', title: 'MSFT has best capital allocation in big tech — dividends, buybacks, smart M&A, Satya is exceptional', body: 'The GitHub acquisition at $7.5B looks like a steal. The Activision deal adds gaming. The OpenAI partnership adds AI. Every deal has compounded.', upvotes: 1432, commentCount: 156, postedAt: hoursAgo(7) },
    { id: 't3_msft04', permalink: 'https://reddit.com/r/investing/comments/msft04', subreddit: 'investing', author: 'activision_skeptic', title: 'Activision acquisition is still a question mark — gaming margins lower than cloud and integration slow', body: 'COD and Game Pass are solid but this is $69B for a business that does not fit neatly into the enterprise software flywheel.', upvotes: 654, commentCount: 189, postedAt: hoursAgo(9) },
    { id: 't3_msft05', permalink: 'https://reddit.com/r/stocks/comments/msft05', subreddit: 'stocks', author: 'teams_dominance', title: 'Teams is replacing Slack and Zoom across corporate America — the bundle strategy is working perfectly', body: 'Why pay separately for Zoom and Slack when Teams is included in your Microsoft 365 subscription? The bundling kills standalone competitors.', upvotes: 1102, commentCount: 145, postedAt: hoursAgo(6) },
    { id: 't3_msft06', permalink: 'https://reddit.com/r/wallstreetbets/comments/msft06', subreddit: 'wallstreetbets', author: 'azure_openai_wins', title: 'Azure OpenAI service wins are massive — every enterprise I talk to is deploying MSFT AI stack', body: 'Spoke with IT directors at 3 different companies this week. All three are on Azure OpenAI. The enterprise distribution advantage is insurmountable.', upvotes: 3210, commentCount: 412, postedAt: hoursAgo(2) },
    { id: 't3_msft07', permalink: 'https://reddit.com/r/stocks/comments/msft07', subreddit: 'stocks', author: 'earnings_preview', title: 'MSFT earnings next week — consensus $3.10 EPS, market reaction will be all about Azure guidance', body: 'If Azure guides above 35% for next quarter the stock gaps up. Below 30% and it sells off regardless of EPS beat.', upvotes: 876, commentCount: 312, postedAt: hoursAgo(10) },
    { id: 't3_msft08', permalink: 'https://reddit.com/r/investing/comments/msft08', subreddit: 'investing', author: 'valuation_check', title: 'At $415 MSFT feels fully valued — growth is real but the multiple leaves no room for error', body: 'Trading at 32x forward earnings for a company this large. Any Azure deceleration or macro headwind could cause a meaningful correction.', upvotes: 765, commentCount: 198, postedAt: hoursAgo(11) },
    { id: 't3_msft09', permalink: 'https://reddit.com/r/SecurityAnalysis/comments/msft09', subreddit: 'SecurityAnalysis', author: 'github_copilot_data', title: 'GitHub Copilot has 1.8M paid subscribers — developer tools monetization is a new high-margin revenue stream', body: 'At $19-$39/month per developer, this is a meaningful and growing business. And it creates MSFT stickiness with the next generation of developers.', upvotes: 987, commentCount: 134, postedAt: hoursAgo(8) },
    { id: 't3_msft10', permalink: 'https://reddit.com/r/investing/comments/msft10', subreddit: 'investing', author: 'decade_holder', title: 'Long MSFT since $100 and not selling — enterprise AI is a decade-long tailwind and MSFT is best positioned', body: 'Every enterprise workflow will have AI embedded in the next 5 years. Microsoft is the operating system for corporate America. That is not changing.', upvotes: 2341, commentCount: 287, postedAt: hoursAgo(4) },
  ],

  GOOGL: [
    { id: 't3_googl01', permalink: 'https://reddit.com/r/stocks/comments/googl01', subreddit: 'stocks', author: 'search_disruption', title: "OpenAI's SearchGPT is real competition — for the first time Google's search dominance is at risk", body: 'I personally switched to Perplexity for half my searches. If I am doing this, millions of others are too. The trend is real.', upvotes: 3210, commentCount: 567, postedAt: hoursAgo(2) },
    { id: 't3_googl02', permalink: 'https://reddit.com/r/investing/comments/googl02', subreddit: 'investing', author: 'gcp_analyst', title: 'Google Cloud grew 35% — finally showing GOOGL has a strong second act beyond search advertising', body: 'GCP is now the fastest growing hyperscaler. The AI infrastructure investments are starting to pay off in enterprise wins.', upvotes: 1543, commentCount: 189, postedAt: hoursAgo(5) },
    { id: 't3_googl03', permalink: 'https://reddit.com/r/SecurityAnalysis/comments/googl03', subreddit: 'SecurityAnalysis', author: 'youtube_monetization', title: 'YouTube is undermonetized relative to TikTok for advertisers — Shorts monetization still developing', body: 'TikTok CPMs have been rising while YouTube Shorts CPMs remain depressed. The short-form video monetization gap is real.', upvotes: 876, commentCount: 145, postedAt: hoursAgo(8) },
    { id: 't3_googl04', permalink: 'https://reddit.com/r/stocks/comments/googl04', subreddit: 'stocks', author: 'gemini_progress', title: 'Gemini 2.0 Ultra is competitive with GPT-4o — Google was behind but has closed the gap significantly', body: 'Google has the compute, the data, and the research talent. The narrative that they are permanently behind in AI was always overdone.', upvotes: 1234, commentCount: 234, postedAt: hoursAgo(6) },
    { id: 't3_googl05', permalink: 'https://reddit.com/r/investing/comments/googl05', subreddit: 'investing', author: 'doj_risk', title: 'DOJ antitrust case is a hard overhang to ignore — forced breakup of search default agreements would be massive', body: 'Apple pays $20B/year to be the default search on Safari. If that ends, Google loses the highest quality mobile traffic. This is existential.', upvotes: 2100, commentCount: 412, postedAt: hoursAgo(4) },
    { id: 't3_googl06', permalink: 'https://reddit.com/r/wallstreetbets/comments/googl06', subreddit: 'wallstreetbets', author: 'value_seeker', title: 'GOOGL at 22x earnings with this growth profile is cheap — one of the better valuations in mega-cap tech', body: 'Google Cloud accelerating, advertising resilient, AI advancing, YouTube growing. And you get Waymo for free. This is undervalued.', upvotes: 2890, commentCount: 356, postedAt: hoursAgo(3) },
    { id: 't3_googl07', permalink: 'https://reddit.com/r/SecurityAnalysis/comments/googl07', subreddit: 'SecurityAnalysis', author: 'waymo_hidden_value', title: 'Waymo is the most undervalued asset in the GOOGL complex — robotaxis scaling in SF, LA, Austin', body: 'Waymo is doing 100K+ rides per week with zero safety drivers. This is not a concept — it is a real business growing fast.', upvotes: 987, commentCount: 178, postedAt: hoursAgo(9) },
    { id: 't3_googl08', permalink: 'https://reddit.com/r/investing/comments/googl08', subreddit: 'investing', author: 'workspace_concern', title: 'Google Workspace losing ground to Microsoft 365 in enterprise — Copilot integration driving switching', body: 'Three enterprise clients I know switched from Google Workspace to M365 this quarter specifically for Copilot features. It is accelerating.', upvotes: 1102, commentCount: 234, postedAt: hoursAgo(10) },
    { id: 't3_googl09', permalink: 'https://reddit.com/r/stocks/comments/googl09', subreddit: 'stocks', author: 'ad_resilience', title: 'Ad revenue beat expectations again — the AI threat to search advertising was overblown', body: 'Advertisers follow intent signals. Google Search has the best intent signals. Even AI-generated summaries drive ad clicks. The model adapts.', upvotes: 1654, commentCount: 198, postedAt: hoursAgo(7) },
    { id: 't3_googl10', permalink: 'https://reddit.com/r/investing/comments/googl10', subreddit: 'investing', author: 'macro_worried', title: 'Holding GOOGL but nervous about next quarter — too many macro crosswinds in digital advertising', body: 'Slowing consumer spending + potential recession fears could hit ad budgets fast. GOOGL is the last to cut but not immune.', upvotes: 654, commentCount: 312, postedAt: hoursAgo(13) },
  ],

  AMZN: [
    { id: 't3_amzn01', permalink: 'https://reddit.com/r/stocks/comments/amzn01', subreddit: 'stocks', author: 'aws_bull', title: 'AWS had another blowout quarter — $25B quarterly revenue and re-accelerating', body: 'AWS growth rate went from 13% to 17% to 21% to 25% over the past year. Enterprise cloud migration cycle is not over.', upvotes: 2890, commentCount: 312, postedAt: hoursAgo(3) },
    { id: 't3_amzn02', permalink: 'https://reddit.com/r/investing/comments/amzn02', subreddit: 'investing', author: 'ads_undervalued', title: "Amazon's advertising business is now $60B run rate growing 20%+ — highly undervalued by market", body: 'Amazon ads are the most effective in ecommerce because you are advertising to people actively shopping. CPMs are premium and growing.', upvotes: 1543, commentCount: 198, postedAt: hoursAgo(5) },
    { id: 't3_amzn03', permalink: 'https://reddit.com/r/SecurityAnalysis/comments/amzn03', subreddit: 'SecurityAnalysis', author: 'margin_expansion', title: "Amazon operating margins hit 11% — highest ever, Jassy's cost discipline is showing up in numbers", body: 'From 2% margins in 2022 to 11% in 2024. The transformation in profitability is as dramatic as any large cap in recent memory.', upvotes: 1876, commentCount: 167, postedAt: hoursAgo(6) },
    { id: 't3_amzn04', permalink: 'https://reddit.com/r/investing/comments/amzn04', subreddit: 'investing', author: 'prime_growth', title: 'Prime membership growth slowing in US but international expansion is picking up — developing markets are next', body: 'Brazil, India, Turkey showing strong Prime adoption. The domestic saturation is a concern but the international opportunity is enormous.', upvotes: 765, commentCount: 145, postedAt: hoursAgo(9) },
    { id: 't3_amzn05', permalink: 'https://reddit.com/r/stocks/comments/amzn05', subreddit: 'stocks', author: 'bedrock_wins', title: 'Bedrock and Amazon Q gaining real traction with enterprise AI — AWS will not cede market to Azure', body: 'AWS customers are using Bedrock for foundation model access. The multi-model approach (Anthropic, Llama, etc.) is actually a differentiator.', upvotes: 1102, commentCount: 178, postedAt: hoursAgo(7) },
    { id: 't3_amzn06', permalink: 'https://reddit.com/r/investing/comments/amzn06', subreddit: 'investing', author: 'healthcare_skeptic', title: "Amazon's healthcare push is still burning cash — unclear when One Medical will be profitable", body: 'One Medical acquisition at $3.9B was expensive. Pharmacy business has thin margins. Healthcare is hard and AMZN has not cracked it yet.', upvotes: 654, commentCount: 212, postedAt: hoursAgo(11) },
    { id: 't3_amzn07', permalink: 'https://reddit.com/r/wallstreetbets/comments/amzn07', subreddit: 'wallstreetbets', author: 'logistics_moat', title: 'AMZN logistics network is becoming a massive competitive moat — third-party delivery margins improving', body: 'Amazon now delivers to 70%+ of the US same-day or next-day for Prime members. Building this would cost any competitor $100B+.', upvotes: 3450, commentCount: 456, postedAt: hoursAgo(2) },
    { id: 't3_amzn08', permalink: 'https://reddit.com/r/SecurityAnalysis/comments/amzn08', subreddit: 'SecurityAnalysis', author: 'kuiper_upside', title: 'Kuiper satellite internet could be a massive business in 5 years — market not pricing this in at all', body: 'SpaceX Starlink proved the market exists. Amazon has distribution relationships globally. If Kuiper works technically, the revenue potential is enormous.', upvotes: 876, commentCount: 134, postedAt: hoursAgo(10) },
    { id: 't3_amzn09', permalink: 'https://reddit.com/r/investing/comments/amzn09', subreddit: 'investing', author: 'cloud_compare', title: 'AMZN vs MSFT vs GOOGL for cloud exposure — which would you pick for a 3-year hold?', body: 'All three are accelerating. AMZN has the largest market share, MSFT has enterprise distribution advantage, GOOGL is cheapest. Tough call.', upvotes: 543, commentCount: 478, postedAt: hoursAgo(12) },
    { id: 't3_amzn10', permalink: 'https://reddit.com/r/stocks/comments/amzn10', subreddit: 'stocks', author: 'flywheel_thesis', title: 'The Amazon flywheel is still spinning — every business segment reinforces the others', body: 'More sellers → more selection → more Prime members → more data → better ads → more seller demand. This compounding is underappreciated.', upvotes: 2134, commentCount: 245, postedAt: hoursAgo(4) },
  ],

  META: [
    { id: 't3_meta01', permalink: 'https://reddit.com/r/stocks/comments/meta01', subreddit: 'stocks', author: 'ad_platform_bull', title: "META's ad platform is the most sophisticated in the world — Advantage+ ROI beats Google for many advertisers", body: 'Spoke with 5 DTC brands this week. All of them said META ads are delivering better ROAS than any other channel in Q1 2025.', upvotes: 2100, commentCount: 287, postedAt: hoursAgo(3) },
    { id: 't3_meta02', permalink: 'https://reddit.com/r/investing/comments/meta02', subreddit: 'investing', author: 'llama_strategy', title: "Llama 4 is open source and competitive with GPT-4o — META's AI strategy is brilliant", body: 'By commoditizing foundation models, META ensures no single competitor can use proprietary AI as a moat against them. Strategic genius.', upvotes: 1876, commentCount: 234, postedAt: hoursAgo(5) },
    { id: 't3_meta03', permalink: 'https://reddit.com/r/wallstreetbets/comments/meta03', subreddit: 'wallstreetbets', author: 'reels_monetization', title: 'Instagram Reels ad revenue now bigger than Stories — TikTok threat has been contained and monetized', body: 'META took the TikTok format and monetized it better than TikTok can. Now they are the incumbent and TikTok ban risk helps them further.', upvotes: 4230, commentCount: 567, postedAt: hoursAgo(2) },
    { id: 't3_meta04', permalink: 'https://reddit.com/r/SecurityAnalysis/comments/meta04', subreddit: 'SecurityAnalysis', author: 'vr_skeptic', title: 'Reality Labs is a $15B per year cash drain — respect the vision but this is shareholder money burning', body: 'Since 2019, Reality Labs has lost $47B. The metaverse has not materialized. At what point does this become untenable for investors?', upvotes: 1543, commentCount: 345, postedAt: hoursAgo(7) },
    { id: 't3_meta05', permalink: 'https://reddit.com/r/investing/comments/meta05', subreddit: 'investing', author: 'valuation_case', title: 'META at 22x earnings with 20%+ EPS growth and buybacks — clearest value/growth combo in mega-cap tech', body: 'The "year of efficiency" transformed the cost structure. Now they have AI tailwinds, buybacks, and reasonable valuation. Hard to argue against.', upvotes: 2341, commentCount: 198, postedAt: hoursAgo(4) },
    { id: 't3_meta06', permalink: 'https://reddit.com/r/stocks/comments/meta06', subreddit: 'stocks', author: 'whatsapp_latam', title: 'WhatsApp Business starting to monetize properly in LatAm and India — this segment going to be massive', body: 'Click-to-WhatsApp ads and business messaging API. In Brazil alone there are 150M WhatsApp users. The monetization is just beginning.', upvotes: 987, commentCount: 156, postedAt: hoursAgo(9) },
    { id: 't3_meta07', permalink: 'https://reddit.com/r/investing/comments/meta07', subreddit: 'investing', author: 'eu_regulatory', title: 'Regulatory environment in Europe getting worse every quarter — GDPR fines and DMA compliance are real headwinds', body: 'Meta has paid over $2B in EU fines since 2022. The pay-or-consent model is being challenged. European revenue growth is constrained.', upvotes: 876, commentCount: 198, postedAt: hoursAgo(10) },
    { id: 't3_meta08', permalink: 'https://reddit.com/r/wallstreetbets/comments/meta08', subreddit: 'wallstreetbets', author: 'threads_growth', title: 'Threads finally has real engagement numbers — legitimate Twitter/X competitor for advertisers', body: 'Threads crossed 200M monthly actives. Not monetized yet but the platform is real. When ads turn on this is a meaningful revenue addition.', upvotes: 3120, commentCount: 423, postedAt: hoursAgo(3) },
    { id: 't3_meta09', permalink: 'https://reddit.com/r/SecurityAnalysis/comments/meta09', subreddit: 'SecurityAnalysis', author: 'zuck_reinvention', title: "Zuckerberg completely reinvented META in 2023 — the year of efficiency was a genuine turning point", body: 'Headcount from 87K to 67K, expense discipline, AI product velocity increased. The pivot from bloated tech giant to lean AI company was real.', upvotes: 1765, commentCount: 213, postedAt: hoursAgo(6) },
    { id: 't3_meta10', permalink: 'https://reddit.com/r/investing/comments/meta10', subreddit: 'investing', author: 'earnings_vol', title: 'META options implied volatility elevated ahead of earnings — expecting a big move either way', body: 'Market pricing 8% move on earnings. If Reality Labs losses shrink AND revenue beats, this could gap up significantly.', upvotes: 1234, commentCount: 312, postedAt: hoursAgo(8) },
  ],
}

export function getMockPostsForTicker(ticker: string): RedditPost[] {
  return MOCK_POSTS[ticker] ?? []
}

export function getAllMockPosts(): Record<string, RedditPost[]> {
  return MOCK_POSTS
}
