export function NarrativeSummary({ narrative }: { narrative: string }) {
  return (
    <div className="glass rounded-[20px] p-6">
      <h3
        className="font-data text-[10px] uppercase tracking-[0.15em] mb-3"
        style={{ color: 'var(--color-text-faint)' }}
      >
        What&apos;s Driving This?
      </h3>
      <p
        className="font-ui text-[17px] leading-relaxed"
        style={{ color: 'var(--color-text)' }}
      >
        {narrative}
      </p>
      <p
        className="font-data text-[10px] mt-4"
        style={{ color: 'var(--color-text-faint)' }}
      >
        Summary generated by AI based on recent news. Not investment advice.
      </p>
    </div>
  )
}
