export function NarrativeSummary({ narrative }: { narrative: string }) {
  return (
    <div className="rounded-lg border border-gray-100 bg-white p-6">
      <h3 className="text-lg font-semibold text-gray-900 mb-3">What&apos;s Driving This?</h3>
      <p className="text-sm text-gray-700 leading-relaxed">{narrative}</p>
      <p className="text-xs text-gray-400 mt-3">
        Summary generated by AI based on the posts above. Not investment advice.
      </p>
    </div>
  )
}
